### ISSUE TITLE
Unable to upgrade from 6.5 to 7.0

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForce#50]
Hello,
I checked below
https://github.com/YetiForceCompany/YetiForceCRM/issues/17437

I am facing same issue where when I upload upgrade file it takes me to home page and do not have any clue. installing fresh instance is not possible.

please assist in the matter

Jeevan Pendhari

**Comment by rskrzypczak** [comment]
Below are some steps that will help you download and install the update pack:

- remove the *.zip files that might have been created directly in the cache folder
- increase the `$timeout` parameter in `app\RequestHttp.php`
it should allow you to download the entire package successfully, if you have a slow internet connection
- go to the panel in the CRM and go through the update process

Remember that YF7 requires a minimum of PHP8.1, so before upgrading to YF7 (before clicking the YES button), switch PHP.
Check logs: `cache/logs/updateLogsTrace.log`, `cache/logs/Importer.log`, `cache/logs/system.log`

**Comment by rskrzypczak** [comment]
Due to lack of activity, the issue has been closed.

**Comment by krzky** [comment]
I have successfully upgrade through changing /var/www/yetiforce/app/RequestHttp.php 
in (public static $timeout = 10) changed to 100
and do the upgrade process with this file https://api.yetiforce.eu/download/crm/UpdatePackages/6.5.0_to_7.0.1_v1 inside logs > System Update

**Comment by JEEVAN28** [comment]
Thanks, I also managed in same way. Thanks again for your help

Regards
Jeevan Pendhari
