### ISSUE TITLE
[YF7.0.2] IMAP servers are not pushed in Config\Modules\OSSMail

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForce#60]
When a new email server (Settings::MailServers backend module) is added/deleted, the OSSMail config file (config/modules/OSSMail.php) is not updated ($imap_host), so IMAPs are not available in RoundCube login page.

**Comment by rskrzypczak** [comment]
Yes, because access to the mailbox works only via autologin. The mentioned configuration file is basically no longer applicable.

In theory, the login view should never appear, if it does, it means that there is an error somewhere (e.g. credentials).

In other words - it is not a bug

**Comment by davide-alghi** [comment]
aaah ok. I just found the setup GUI in user preferences.
tnx Radosław
I'm going to close this issue

**Comment by davide-alghi** [comment]
@rskrzypczak 
just a note: in apache site, in "Content-Security-Policy" header I had to set it up 'unsafe-eval' in 'script-src' directive, otherwise the emails are not listed. browser's console notifies it.
