### ISSUE TITLE
[YF7.0.2] JavaScript recursive loop in user preferences

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForce#66]
Changing the `Decimal separator` field in the user preferences to the same value as `Digit grouping separator`, or vice versa, generates a large number of notifications.

This issues a recursive loop in JavaScript.

![Schermata del 2024-11-25 16-58-15](https://github.com/user-attachments/assets/210b5228-9a42-44e7-a4e6-ad2881d08a0a)
![Schermata del 2024-11-25 17-02-17](https://github.com/user-attachments/assets/d5b92fa4-7766-4119-9e50-7239b3b774ff)

**Comment by rskrzypczak** [comment]
This bug has been fixed in version 7.0.1, so it does not occur in version 7.0.2 as you suggest in the subject of this issue, but in 7.0.0 as you can see in the attached screenshot.

Due to the above, I am closing the issue.
I recommend updating the system ;)

**Comment by davide-alghi** [comment]
OOOPS, sorry. u r right: I was working on 701: 702 fixes it. updated tnx
